{
 "title": "Fabbrica di Biscotti",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Produzione al minuto",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"counter\")\r\n  |> aggregateWindow(every: 1m, fn: sum, column: \"_value\", createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Totale biscotti prodotti",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"counter\")\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Produzione al Minuto Media",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"counter\")\r\n  |> aggregateWindow(every: 1m, fn: sum, column: \"_value\", createEmpty: false)\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Velocità Nastro Trasportatore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"conveyor_speed\")\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Velocità Media Nastro Trasportatore",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"conveyor_speed\")\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Velocità Nastro Trasportatore",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"conveyor_speed\")\r\n  |> filter(fn: (r) => r.speed_cat == \"high_speed\" or r.speed_cat == \"low_speed\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> tail(n: 1)\r\n  |> max(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Forno Error Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"oven_door\" and r._field == \"is_okay\")\r\n  |> group(columns: [\"_value\"], mode: \"by\")\r\n  |> count(column: \"_field\")"
    }
   ]
  },
  {
   "title": "Aperture Forno",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"grafana_test\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"oven_door\")\r\n"
    }
   ]
  }
 ]
}